### ISSUE TITLE
ios 10 tab文字消失了。 

### ISSUE THREAD

**Issue by monkeyRing** [teambition/SegmentedControl#5]
没有截图。 
如题： iOS 10 分段控件上的文字没了，但是下划线有。 其他一切正常 仅仅文字不显示，正常状态 和选中状态都是如此。iOS 10 以前正常。麻烦兄台看看

**Comment by hongxinhope** [comment]
I have fixed this issue one month ago in [release 0.0.5](https://github.com/teambition/SegmentedControl/releases/tag/0.0.5), did you use the latest version?

**Comment by monkeyRing** [comment]
ok thx
